// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drqsjwkzyiqldwcjwuey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRycXNqd2t6eWlxbGR3Y2p3dWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzI4ODgsImV4cCI6MjA2NDAwODg4OH0.XKj7Q6I8RBjjIqlBU2hYC5OSUcl5Ypf0lOrz7ES4zB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);